### PR TITLE
CEPHSTORA-441 Upgrade ceph-ansible to v3.1.9

### PR DESCRIPTION
**Pull request by mvollman**
Upgrade ceph-ansible from v3.0.46 to v3.1.9 and update our dependency
tracking script to track v3.1 of ceph-ansible going forward.

### CODE REVIEW

**Comment by mvollman** [comment]
Added WIP to hopefully prevent merging.  Deployment works fine, but taking over an existing cluster currently fails on the ceph_key module.  Looking into the issue.  Please do not merge.

**Comment by mvollman** [comment]
:shipit:

**Comment by mvollman** [comment]
:shipit:

**Comment by corystone** [comment]
One of those squirrels is obviously an impostor.

**Pull request merged**
