### PR TITLE
CEPHSTORA-443 Add rpco_rocky scenario

### PR DESCRIPTION
**Pull request by mvollman**
Update tests to support rpco rocky scenario

### CODE REVIEW

**Comment by odyssey4me** [comment]
recheck_container_ansible_lint_test verifying recent changes in rpc-gating haven't broken anything

**Comment by letterj** [comment]
recheck_container_ansible_lint_test

**Comment by odyssey4me** [comment]
recheck_container_ansible_lint_test verifying recent changes in rpc-gating haven't broken anything

**Comment by odyssey4me** [comment]
Testing done, please feel free to merge when you feel this should be.

**Comment by mvollman** [comment]
:shipit:

**Pull request merged**
