### PR TITLE
Feature/cpufreq

### PR DESCRIPTION
**Pull request by mvollman**

### CODE REVIEW

**Comment by letterj** [comment]
@mheler  Would you mind sharing with us the appropriate way?

**Comment by mheler** [comment]
With this method we would have to rerun the playbooks each time we do a reboot. That's not a solution, and that would never happen in production. We reboot nodes to replace faulty hardware or apply new kernels. Please find another solution to this.

**Comment by letterj** [comment]
@mheler I think everyone could understand your comment "This is not persistent between reboots. Not an appropriate way to do this." the first time   but thank you for rehashing it again.  Super helpful.  It seems that by your inability to answer my question and reply with just a simple wordier rehash of your previous comment  you don't have a suggestion for doing it another way.

**Comment by mvollman** [comment]
Good catch.  I will modify the play so it is persistent.

**Comment by mheler** [comment]
@letterj that is an inappropriate response. Going further you can expect less help from support.

**Comment by BjoernT** [comment]
The cpufreq directory is not existing for Ubuntu 16.04 I have seen this is being replaced with policy, per cpu. The scaling governor is available underneath it

**Comment by mheler** [comment]
This PR shouldn't include sysctl changes. Why are these values being removed? Especially pidmax, which prevents issues on long running ceph nodes.

**Comment by mvollman** [comment]
@mheler I noticed that these values were all being passed twice in os_tuning_params.  I am simply removing duplicate declarations.

**Comment by mheler** [comment]
@mvollman That's fine.. but to @BjoernT point the sysfs in newer kernels changes to this format
/sys/devices/system/cpu/cpufreq/policy0/scaling_governor

So the code we have here will not work with the latest Ubuntu 16.04 installs.

**Comment by mvollman** [comment]
@mheler I did see @BjoernT comment and checked on the latest 16.04 install and the symbolic link is still maintained from each logical cpu back to its given policy.  I checked the linux kernel doc and it says that the symbolic link will continue to be there for each cpu.  So using the link allows us to dynamically set the active policy cpufreq albeit multiple times.  However I am fine with setting it at the policy level instead, I will make this change and push it up.

**Comment by mheler** [comment]
@mvollman let me discuss this with Bjoern on Monday, as this may not be the path we want to move forward with here. How we do this in rpc-ceph needs to align with the way we do this in RPC-O. Currently there is a playbook that I made which is used by various dedicated architects to apply persistent CPU governor changes for there customers.

**Comment by mvollman** [comment]
Sounds good to me.  I was just trying to quickly capture the work that was being done to tune the clusters since I had been doing this manually each time outside of source control.  If we have an existing method I would be happy to use that instead.

**Comment by mheler** [comment]
@mvollman This is the playbook I made a while back that a few of our dedicated arch's are using with there customers [1]. If we can port this into rpc-ceph, that would be great. One thing is that we really should be using handlers to restart services. But being that this was a standalone playbook, it wasn't worth implementing. However with rpc-ceph it should be implemented this way.

Let me know if you have questions. 

[1]
https://gist.github.com/mheler/6671bd92fba9cab1eb4ead4ecb6388e9

**Comment by mvollman** [comment]
recheck_cit_xenial_functional_test

**Pull request merged**
