### PR TITLE
CEPHSTORA-111 Move Rsyslog-server playbook to playbooks dir

### PR DESCRIPTION
**Pull request by andymcc**

### CODE REVIEW

**Comment by andymcc** [comment]
recheck_cit_xenial_rgw_test

**Comment by andymcc** [comment]
recheck_cit_xenial_keystone_rgw_test

**Comment by andymcc** [comment]
recheck_cit_xenial_keystone_rgw_test

**Comment by andymcc** [comment]
recheck_cit_xenial_keystone_rgw_test

**Comment by letterj** [comment]
LGTM

**Pull request merged**
