### PR TITLE
Allow Override group_vars

### PR DESCRIPTION
**Pull request by andymcc**
To ensure that customer specific vars can be set in group_vars, we
should create a group_vars directory per host group. This will allow a
group_vars/all/overrides.yml to take precedence.

This file will be ignored by git so the repo can be updated without
overwriting vars or creating merge conflicts which would result from
editing the "00-defaults.yml" file.

### CODE REVIEW

**Comment by andymcc** [comment]
recheck_cit_xenial_fucntional_test

**Comment by andymcc** [comment]
recheck_cit_xenial_functional_test

**Comment by letterj** [comment]
This doc will need to be amended based on these changes  https://github.com/rcbops/rpc-ceph/blob/master/docs/rgw_setup.md baed

**Comment by andymcc** [comment]
recheck_cit_xenial_keystone_rgw_test

**Comment by letterj** [comment]
LGTM

**Pull request merged**
