### PR TITLE
[CEPHSTORA-18] Add FIO benchmark playbook

### PR DESCRIPTION
**Pull request by andymcc**
Adds fio tests based on EBS benchmark procedures:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/benchmark_procedures.html

Adds a run of the ebs_benchmark to testing.

### CODE REVIEW

**Comment by andymcc** [comment]
Not ready quite yet.

**Comment by andymcc** [comment]
Also still TODO: Fix block size for fio config  and add the ssd tests from the ebs page.

**Comment by andymcc** [comment]
Still needs cleanup of the fiobench user in ceph.

**Comment by galstrom21** [comment]
👍 LGTM

**Comment by andymcc** [comment]
recheck_cit_xenial_master

**Pull request merged**
