### PR TITLE
Bump to Ansible 2.4.3

### PR DESCRIPTION
**Pull request by andymcc**
Some minor fixes to modules in Ansible were added, lets move to use
version 2.4.3.

### CODE REVIEW

**Comment by andymcc** [comment]
recheck_cit_xenial_keystone_rgw_test

**Comment by andymcc** [comment]
failing on some ubuntu repo issues (hashsum mismatch)

**Comment by andymcc** [comment]
recheck_cit_xenial_keystone_rgw_test

**Comment by andymcc** [comment]
recheck_cit_xenial_keystone_rgw_test

**Comment by letterj** [comment]
LGTM

**Pull request merged**
