### PR TITLE
Adding repo servers group to inventory-sample

### PR DESCRIPTION
**Pull request by srkreddy**
CEPHSTORA-540: Adding repo_severs and haproxy_all groups to inventory-sample

### CODE REVIEW

**Comment by mvollman** [comment]
Lets add haproxy_all to the sample file as well.  Also if you start your commit message with the jira issue ID it will link back to the jira issue.

**Comment by srkreddy** [comment]
> Lets add haproxy_all to the sample file as well. Also if you start your commit message with the jira issue ID it will link back to the jira issue.

Updated PR with requested changes @mvollman

**Comment by mvollman** [comment]
Can you squash this into a single commit please?

**Comment by srkreddy** [comment]
squashed the commits @mvollman

**Comment by srkreddy** [comment]
recheck_xenial_functional_test

**Pull request merged**
